accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "MIT-0",
    "Unicode-3.0",
    "Zlib",
    "CC0-1.0",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
    "BSL-1.0",
]

ignore-transitive-dependencies = false

private = { ignore = true }
