[package]
name = "curveball-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-colors = "0.3.0"
clap = { version = "4.5.23", features = ["derive"] }
curveball-lib = { path = "../curveball-lib" }
