[package]
name = "lib-curveball"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chull = "0.2.4"
glam = { version = "0.30.0", features = ["debug-glam-assert"] }
itertools = "0.14.0"
lerp = "0.5.0"
thiserror = "2.0.9"
